name: create cicd application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  AWS_REGION: "eu-west-1"
  ECS_REPOSITORY: "${{vars.REPO_NAME}}"

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - run: echo "heelo pratik"
      - run: echo "kya kr rhe"
  test:
    runs-on: ubuntu-slim
    steps:
      - run: echo "using secret"
      - run: echo "${{secrets.NAME}}"
  deploy:
    runs-on: ubuntu-slim
    steps:
      - run: echo "using environment variable"
      - run: echo "region is $AWS_REGION"
      - run: echo "repository is $ECS_REPOSITORY"
