name: create cicd application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  AWS_REGION: "eu-west-1"
  

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4
      - run: echo "heelo pratik"
      - run: echo "kya kr rhe"
  test:
    runs-on: ubuntu-slim
    steps:
      - run: echo "using secret"
      - run: echo "${{secrets.NAME}}"
      - name: instal node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: node --version
      - run: |
          echo "sleeping for 10 seconds before deploy"
          sleep 10
  deploy:
    runs-on: ubuntu-slim
    steps:
      - run: echo "using environment variable"
      - run: echo "region is $AWS_REGION"
      - run: echo "repository is ${{vars.REPO_NAME}}"
